#!/bin/bash

refname="$1"
oldrev="$2"
newrev="$3"
GIT_SSH='ssh -i /var/opt/gitlab/git-data/repositories/lv239/Ansible-playbooks.git/id_rsa'
while read oldrev newrev ref
do
  cd /tmp/repo
  git clone git@github.com:MikeGreyDog/Gitlab-backups.git 

  sudo rm -rf Gitlab-backups/Old-Backup
  sudo mv Gitlab-backups/Previous-Backup Gitlab-backups/Old-Backup
  sudo mv Gitlab-backups/New-Backup Gitlab-backups/Previous-Backup
  mkdir Gitlab-backups/New-Backup

  sudo gitlab-rake gitlab:backup:create
  cd Gitlab-backups

  unset GIT_DIR
  git add .
  git commit -m "New backup added: $(date '+%d%m%Y_%H:%M:%S')"
  git push origin master

done 
 exit 0



